services:
    sonata.admin.article:
        class: AppBundle\Admin\ArticleAdmin
        arguments: [~, AppBundle\Entity\Article, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Article", label: "Articles" }
    sonata.admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Article", label: "Categories" }
    sonata.admin.tag:
        class: AppBundle\Admin\TagAdmin
        arguments: [~, AppBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Article", label: "Tags" }
    sonata.admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "User", label: "Users" }